language: python
python:
  - "2.7"
# command to install dependencies
install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n diags_viewer --file ea/conda_reqs.txt -c uvcdat
  - source activate diags_viewer
  - pip install -r ea/pip_reqs.txt
script: echo "Done."